### ISSUE TITLE
编码有问题

### ISSUE THREAD

**Issue by Eileen456123** [RMSnow/WWW2021#3]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 30: invalid start byte

**Comment by RMSnow** [comment]
Could you write more details (eg: post your code) about this bug?

**Comment by Eileen456123** [comment]
Traceback (most recent call last):
  File "D:/PycharmProjects/WWW2021-master/code/preprocess/output_of_labels.py", line 43, in <module>
    data_dir, '{}.json'.format(t)), 'r')) for t in ['train', 'val', 'test']]
  File "D:/PycharmProjects/WWW2021-master/code/preprocess/output_of_labels.py", line 43, in <listcomp>
    data_dir, '{}.json'.format(t)), 'r')) for t in ['train', 'val', 'test']]
  File "D:\software\Anaconda3\envs\WWW2021-master\lib\json\__init__.py", line 296, in load
    return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0x90 in position 30: illegal multibyte sequence

Process finished with exit code 1

**Comment by Eileen456123** [comment]
`我直接按照你的readme执行output_of_labels.py文件，直接就报了以下错误：`

Traceback (most recent call last):
File "D:/PycharmProjects/WWW2021-master/code/preprocess/output_of_labels.py", line 43, in
data_dir, '{}.json'.format(t)), 'r')) for t in ['train', 'val', 'test']]
File "D:/PycharmProjects/WWW2021-master/code/preprocess/output_of_labels.py", line 43, in
data_dir, '{}.json'.format(t)), 'r')) for t in ['train', 'val', 'test']]
File "D:\software\Anaconda3\envs\WWW2021-master\lib\json_init_.py", line 296, in load
return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0x90 in position 30: illegal multibyte sequence

Process finished with exit code 1

**Comment by RMSnow** [comment]
你是否改变了数据文件（json文件）的编码方式？这些json文件需要用utf-8格式来读取。你先尝试一下，例如：

```
with open('../../dataset/Weibo-20/test.json', 'r', encoding='utf-8') as f:
    test = json.load(f)
```

看看这两行代码，是否可以读取。

**Comment by Eileen456123** [comment]
你是否改变了数据文件（json文件）的编码方式？这些json文件需要用utf-8格式来读取。你先尝试一下，例如：

with open('../../dataset/Weibo-20/test.json', 'r', encoding='utf-8') as f:
    test = json.load(f)
看看这两行代码，是否可以读取。

试了你以上的代码可以正常读取，数据集我是下载下来没有改动过的。那下一步该怎么弄

split_datasets = [json.load(open(os.path.join(
        data_dir, '{}.json'.format(t)), 'r')) for t in ['train', 'val', 'test']]  在这行代码‘r’后面加encoding='utf-8'这个吗？

我加了是可以运行，可是生成了lable，但是生成了lable,我打开随便一个.npy文件它都显示File was loaded in the wrong enconding:'UTF-8'

我继续运行input_of_emotions.py文件时候，又报了以下错误
Traceback (most recent call last):
  File "D:/PycharmProjects/WWW2021-master/code/preprocess/input_of_emotions.py", line 67, in <module>
    json.dump(pieces, f, indent=4, ensure_ascii=False)
  File "D:\software\Anaconda3\envs\WWW2021-master\lib\json\__init__.py", line 180, in dump
    fp.write(chunk)
UnicodeEncodeError: 'gbk' codec can't encode character '\ue107' in position 20: illegal multibyte sequence

Process finished with exit code 1

**Comment by RMSnow** [comment]
1. "随便打开一个.npy文件"是指什么？
```
>>> import numpy as np
>>> test = np.load('./data/Weibo-20/labels/test_(1274, 2).npy')
>>> test.shape
(1274, 2)
```
上述代码，我这里可以正常运行。

2. 同理，在`input_of_emotions.py`的第66行，添加encoding='utf-8'

**Comment by Eileen456123** [comment]
我在input_of_emotions.py的第66行，添加encoding='utf-8'了后：

控制台输出如下：

The num of negation words:  44
The num of degree words:  214 . eg:  (b'\xe7\x99\xbe\xe5\x88\x86\xe4\xb9\x8b\xe7\x99\xbe', 2.0)
[Dalianligong]	There are 27351 words, the dimension is (29,)
[BosonNLP]	 There are 114766 words
[Emoticon]	There are 104 emoticons, including 5 categories
[HowNet]	There are 4528 positive words and 4320 negative words

The num of negation words:  26
The num of degree words:  157 . eg:  ('100 percent', 2.0)
[NRC Lexicon]	There are 14182 words, including 10 categories, every term's dimension is (10,)
[NRC Intensity]	There are 5975 words, including 8 categories, every term's dimension is (8,)

File: 正面情感词语（英文）.txt, Words_sz = 769
File: 正面评价词语（英文）.txt, Words_sz = 3594
File: 负面情感词语（英文）.txt, Words_sz = 1011
File: 负面评价词语（英文）.txt, Words_sz = 3563
[HowNet]	There are 4349 positive words and 4534 negative words
File: 1-personal-pronoun.txt, Words_sz = 8
File: 2-personal-pronoun.txt, Words_sz = 3
File: 3-personal-pronoun.txt, Words_sz = 12


-------------------- [2021-08-01 20:31:58]	Processing the dataset: Weibo-16 --------------------

[2021-08-01 20:31:59]	Words Cutting...
  0%|          | 0/2211 [00:00<?, ?it/s]Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\Eileen\AppData\Local\Temp\jieba.cache
Loading model cost 0.844 seconds.
Prefix dict has been built successfully.
100%|██████████| 2211/2211 [01:50<00:00, 19.94it/s]
  0%|          | 0/2211 [00:00<?, ?it/s]Traceback (most recent call last):
  File "D:/PycharmProjects/WWW2021-master/code/preprocess/input_of_emotions.py", line 70, in <module>
    p) for p in tqdm(pieces)]
  File "D:/PycharmProjects/WWW2021-master/code/preprocess/input_of_emotions.py", line 70, in <listcomp>
    p) for p in tqdm(pieces)]
  File "D:\PycharmProjects\WWW2021-master\code\emotion\extract_emotion_ch.py", line 294, in extract_dual_emotion
    piece['content'], piece['content_words'], piece['content_emotions'])
  File "D:\PycharmProjects\WWW2021-master\code\emotion\extract_emotion_ch.py", line 264, in extract_publisher_emotion
    arr[8:37] = dalianligong_arr(cut_words)
  File "D:\PycharmProjects\WWW2021-master\code\emotion\extract_emotion_ch.py", line 89, in dalianligong_arr
    not_v, how_v = get_not_and_how_value(cut_words, i, windows)
  File "D:\PycharmProjects\WWW2021-master\code\emotion\extract_emotion_ch.py", line 63, in get_not_and_how_value
    if w in window_text:
TypeError: 'in <string>' requires string as left operand, not bytes
  0%|          | 0/2211 [00:00<?, ?it/s]

Process finished with exit code 1

**Comment by Eileen456123** [comment]
>>> import numpy as np
>>> test = np.load('./data/Weibo-20/labels/test_(1274, 2).npy')
>>> test.shape
(1274, 2)
这没问题了

我在input_of_emotions.py的第66行，添加encoding='utf-8'了后：

控制台输出如下：

The num of negation words: 44
The num of degree words: 214 . eg: (b'\xe7\x99\xbe\xe5\x88\x86\xe4\xb9\x8b\xe7\x99\xbe', 2.0)
[Dalianligong] There are 27351 words, the dimension is (29,)
[BosonNLP] There are 114766 words
[Emoticon] There are 104 emoticons, including 5 categories
[HowNet] There are 4528 positive words and 4320 negative words

The num of negation words: 26
The num of degree words: 157 . eg: ('100 percent', 2.0)
[NRC Lexicon] There are 14182 words, including 10 categories, every term's dimension is (10,)
[NRC Intensity] There are 5975 words, including 8 categories, every term's dimension is (8,)

File: 正面情感词语（英文）.txt, Words_sz = 769
File: 正面评价词语（英文）.txt, Words_sz = 3594
File: 负面情感词语（英文）.txt, Words_sz = 1011
File: 负面评价词语（英文）.txt, Words_sz = 3563
[HowNet] There are 4349 positive words and 4534 negative words
File: 1-personal-pronoun.txt, Words_sz = 8
File: 2-personal-pronoun.txt, Words_sz = 3
File: 3-personal-pronoun.txt, Words_sz = 12

-------------------- [2021-08-01 20:31:58] Processing the dataset: Weibo-16 --------------------

[2021-08-01 20:31:59] Words Cutting...
0%| | 0/2211 [00:00<?, ?it/s]Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\Eileen\AppData\Local\Temp\jieba.cache
Loading model cost 0.844 seconds.
Prefix dict has been built successfully.
100%|██████████| 2211/2211 [01:50<00:00, 19.94it/s]
0%| | 0/2211 [00:00<?, ?it/s]Traceback (most recent call last):
File "D:/PycharmProjects/WWW2021-master/code/preprocess/input_of_emotions.py", line 70, in
p) for p in tqdm(pieces)]
File "D:/PycharmProjects/WWW2021-master/code/preprocess/input_of_emotions.py", line 70, in
p) for p in tqdm(pieces)]
File "D:\PycharmProjects\WWW2021-master\code\emotion\extract_emotion_ch.py", line 294, in extract_dual_emotion
piece['content'], piece['content_words'], piece['content_emotions'])
File "D:\PycharmProjects\WWW2021-master\code\emotion\extract_emotion_ch.py", line 264, in extract_publisher_emotion
arr[8:37] = dalianligong_arr(cut_words)
File "D:\PycharmProjects\WWW2021-master\code\emotion\extract_emotion_ch.py", line 89, in dalianligong_arr
not_v, how_v = get_not_and_how_value(cut_words, i, windows)
File "D:\PycharmProjects\WWW2021-master\code\emotion\extract_emotion_ch.py", line 63, in get_not_and_how_value
if w in window_text:
TypeError: 'in ' requires string as left operand, not bytes
0%| | 0/2211 [00:00<?, ?it/s]

Process finished with exit code 1

如何解决呢
